[build]
# Node.js version specify karein
node_version = "18"

[phases]
# Build phase mein commands specify karein
build = "npm install"

[start]
# Start command specify karein
start = "node index.js"
